version: "3.8"

services:
  server:
    build: ./server.diss-cuss
    container_name: server
    ports:
      - "5000" # exposed to internal network only
    depends_on:
      - db
    env_file:
      - ./server.diss-cuss/.env.production
    environment:
      BACKEND_BASE_URL: "https://api.diss-cuss.xyz"
      NEXT_BASE_URL: "https://www.diss-cuss.xyz"
    volumes:
      - /app/node_modules
    restart: unless-stopped

  db:
    image: postgres:14
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nitinrana1234
      POSTGRES_DB: diss_cuss
    volumes:
      - db-data:/var/lib/postgresql/data

  nginx:
    image: nginx:stable
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443" # Required for HTTPS
    volumes:
      - ./nginx/api.diss-cuss.xyz.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro # mount real certs
    depends_on:
      - server

volumes:
  db-data:
