services:
  server:
    build: ./server.diss-cuss
    ports:
      - "5000:5000"
    depends_on:
      - db
    env_file:
      - ./server.diss-cuss/.env.production
    environment:
      DATABASE_URL: "postgresql://postgres:nitinrana1234@db:5432/diss_cuss"
      PORT: 5000
      BACKEND_BASE_URL: "http://server:5000"
      NEXT_BASE_URL: "https://diss-cuss.vercel.app"
    volumes:
      - ./server.diss-cuss:/app
      - /app/node_modules

  db:
    image: postgres:14
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nitinrana1234
      POSTGRES_DB: diss_cuss
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
