version: "3.8"

services:
  server:
    build: ./server.diss-cuss
    ports:
      - "5000"
    depends_on:
      - db
    env_file:
      - ./server.diss-cuss/.env.production
    environment:
      BACKEND_BASE_URL: "https://diss-cuss.duckdns.org"
      NEXT_BASE_URL: "https://diss-cuss.vercel.app"
    volumes:
      - /app/node_modules

  db:
    image: postgres:14
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nitinrana1234
      POSTGRES_DB: diss_cuss
    volumes:
      - db-data:/var/lib/postgresql/data

  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - server
    restart: always

volumes:
  db-data:
  caddy_data:
  caddy_config:
